php-fpm:
    build: php-fpm
    ports:
        - 9000:9000
    volumes:
        - ./application:/var/www/html/
    links:
        - db
nginx:
    build: nginx
    ports:
        - 8080:80
    volumes:
        - ./application:/var/www/html/        
    links:
        - php-fpm
db:
    image: mysql
    ports:
        - 3308:3306
    environment:
        MYSQL_DATABASE: laravel-rest3
        MYSQL_USER: laravel-user
        MYSQL_PASSWORD: 123456
        MYSQL_ROOT_PASSWORD: qwerty
